// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ReviewFormController from "./review_form_controller"
application.register("review-form", ReviewFormController)

import ReviewChartController from "./review_chart_controller"
application.register("review-chart", ReviewChartController)

import ReviewDetailChartController from "./review_detail_chart_controller"
application.register("review-detail-chart", ReviewDetailChartController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import AutoModalController from "./auto_modal_controller"
application.register("auto-modal", AutoModalController)

import CharCounterController from "./char_counter_controller"
application.register("char-counter", CharCounterController)
